### ISSUE TITLE
GUI dialogue label correction

### ISSUE THREAD

**Issue by mantisgb** [PaloAltoNetworks/panos-bootstrapper-ui#5]
Bootstrapper > Build Bootstrap Archive > [choose Amazon S3 Bucket] > Submit the dialogue asks for "Amazon S3 Key API". I think this should say "AWS Access Key" and then next dialogue say "AWS Secret Key" instead it says "Aws secret".

**Comment by nembery** [comment]
fixed via commit: a0fbf21d2a890c31d039801dd999c5f4431a4420

Thanks for the report!
